### ISSUE TITLE
Asks for License key

### ISSUE THREAD

**Issue by Salty-Coder** [Hussaryn/Orcus-1.9.1-src#4]
`Orcus.Administration\bin\Debug\Orcus.Administration.exe` asks for license key but submit button is disabled

**Comment by Hussaryn** [comment]
https://cracked.to/Thread-Leak-C-Orcus-1-9-1-RAT-Full-Source-Code-Leaked?page=3
check my response

**Comment by Salty-Coder** [comment]
> https://cracked.to/Thread-Leak-C-Orcus-1-9-1-RAT-Full-Source-Code-Leaked?page=3
> 
> check my response

That's worked but I'm now having a new issue. When connecting to the server, I'm getting a mix of `Connection refused` and something like the connection was forcibly closed by the remote.

On the server it's just showing `The credentials supplied to the package were not recognised`

**Comment by Salty-Coder** [comment]
> > https://cracked.to/Thread-Leak-C-Orcus-1-9-1-RAT-Full-Source-Code-Leaked?page=3
> > 
> > check my response
> 
> That's worked but I'm now having a new issue. When connecting to the server, I'm getting a mix of `Connection refused` and something like the connection was forcibly closed by the remote.
> 
> On the server it's just showing `The credentials supplied to the package were not recognised`

Never mind I fixed it by running it not in sandbox
